<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>pri.web_api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="sql\status.sql" />
    <None Remove="sql\status_alter.sql" />
    <None Remove="sql\pri_site_daily_ingest.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sql\status.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="sql\status_alter.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Include="sql\pri_site_daily_ingest.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.sqlserver" Version="9.0.3" /> 
  </ItemGroup>

</Project>
